class GameMap:
 game_map = {'nierautomata': 'NieR: Automata',
 'stardewvalley': 'Stardew Valley',
 'divinityoriginalsiniidefinitiveedition': 'Divinity: Original Sin 2 - Definitive Edition',
 'portalii': 'Portal 2',
 'witcheriiiwildhunt': 'The Witcher 3: Wild Hunt',
 'falloutiv': 'Fallout 4',
 'rimworld': 'RimWorld',
 'terraria': 'Terraria',
 'elderscrollsvskyrim': 'The Elder Scrolls V: Skyrim',
 'grandtheftautov': 'Grand Theft Auto V',
 'leftivdeadii': 'Left 4 Dead 2',
 'portal': 'Portal',
 'cyberpunkii0viivii': 'Cyberpunk 2077',
 'borderlandsii': 'Borderlands 2',
 'tombraider': 'Tomb Raider',
 'bioshockinfinite': 'BioShock Infinite',
 'nomanssky': "No Man's Sky",
 'factorio': 'Factorio',
 'cuphead': 'Cuphead',
 'doom': 'DOOM',
 'sidmeierscivilizationv': "Sid Meier's Civilization V",
 'halflifeii': 'Half-Life 2',
 'elderscrollsvskyrimspecialedition': 'The Elder Scrolls V: Skyrim Special Edition',
 'dishonored': 'Dishonored',
 'deadcells': 'Dead Cells',
 'falloutnewvegas': 'Fallout: New Vegas',
 'citiesskylines': 'Cities: Skylines',
 'hollowknight': 'Hollow Knight',
 'halflifeiilostcoast': 'Half-Life 2: Lost Coast',
 'bastion': 'Bastion',
 'discoelysium': 'Disco Elysium',
 'darksoulsiii': 'Dark Souls III',
 'sekiroshadowsdietwice': 'Sekiro: Shadows Die Twice',
 'amnesiadarkdescent': 'Amnesia: The Dark Descent',
 'undertale': 'Undertale',
 'starbound': 'Starbound',
 'counterstrikeglobaloffensive': 'Counter-Strike: Global Offensive',
 'rocketleague': 'Rocket League',
 'limbo': 'LIMBO',
 'witcheriiassassinsofkingsenhancededition': 'The Witcher 2: Assassins of Kings Enhanced Edition',
 'dishonoredii': 'Dishonored 2',
 'ftlfasterthanlight': 'FTL: Faster Than Light',
 'xcomii': 'XCOM 2',
 'metroii0iiiiii': 'Metro 2033',
 'kerbalspaceprogram': 'Kerbal Space Program',
 'riseoftombraiderii0yearcelebration': 'Rise of the Tomb Raider: 20 Year Celebration',
 'subnautica': 'Subnautica',
 'metalgearsolidvphantompain': 'METAL GEAR SOLID V: THE PHANTOM PAIN',
 'reddeadredemptionii': 'Red Dead Redemption 2',
 'xcomenemyunknown': 'XCOM: Enemy Unknown',
 'walkingdead': 'The Walking Dead',
 'oriandblindforestdefinitiveedition': 'Ori and the Blind Forest: Definitive Edition',
 'blackmesa': 'Black Mesa',
 'stanleyparable': 'The Stanley Parable',
 'garrysmod': "Garry's Mod",
 'psychonauts': 'Psychonauts',
 'batmanarkhamcitygameofyearedition': 'Batman Arkham City Game of the Year Edition',
 'papersplease': 'Papers, Please',
 'divinityoriginalsinenhancededition': 'Divinity: Original Sin Enhanced Edition',
 'sidmeierscivilizationvi': "Sid Meier's Civilization VI",
 'darkestdungeon': 'Darkest Dungeon',
 'specopsline': 'Spec Ops: The Line',
 'saintsrowthird': 'Saints Row: The Third',
 'crusaderkingsii': 'Crusader Kings II',
 'halflifeiiepisodeone': 'Half-Life 2: Episode One',
 'dyinglight': 'Dying Light',
 'torchlightii': 'Torchlight II',
 'halflifeiiepisodetwo': 'Half-Life 2: Episode Two',
 'batmanarkhamasylumgameofyearedition': 'Batman: Arkham Asylum Game of the Year Edition',
 'longdark': 'The Long Dark',
 'firewatch': 'Firewatch',
 'lifeisstrangeepisodei': 'Life is Strange Episode 1',
 'talosprinciple': 'The Talos Principle',
 'thiswarofmine': 'This War of Mine',
 'hellbladesenuassacrifice': "Hellblade: Senua's Sacrifice",
 'mirrorsedge': "Mirror's Edge",
 'bioshockremastered': 'BioShock Remastered',
 'magicka': 'Magicka',
 'preyii0ivii': 'Prey (2017)',
 'justcauseii': 'Just Cause 2',
 'transistor': 'Transistor',
 'companyofheroesii': 'Company of Heroes 2',
 'borderlandspresequel': 'Borderlands: The Pre-Sequel',
 'darksoulspreparetodieedition': 'Dark Souls™: Prepare To Die™ Edition',
 'rust': 'Rust',
 'dontstarvetogether': "Don't Starve Together",
 'stellaris': 'Stellaris',
 'wolfensteinneworder': 'Wolfenstein The New Order',
 'brutallegend': 'Brutal Legend',
 'shadowwarrior': 'Shadow Warrior',
 'tabletopsimulator': 'Tabletop Simulator',
 'prisonarchitect': 'Prison Architect',
 'tropicoiv': 'Tropico 4',
 'witcherenhancededitiondirectorscut': "The Witcher: Enhanced Edition Director's Cut",
 'trineiicompletestory': 'Trine 2: Complete Story',
 'killingfloor': 'Killing Floor',
 'deusexmankinddivided': 'Deus Ex: Mankind Divided',
 'insurgency': 'INSURGENCY',
 'hotlinemiami': 'Hotline Miami',
 'inside': 'INSIDE',
 'outlast': 'Outlast',
 'astroneer': 'ASTRONEER',
 'supermeatboy': 'Super Meat Boy',
 'justcauseiii': 'Just Cause 3',
 'theforest': 'The Forest',
 'oxygennotincluded': 'Oxygen Not Included',
 'darksiderswarmasterededition': 'Darksiders Warmastered Edition',
 'superhot': 'SUPERHOT',
 'monsterhunterworld': 'Monster Hunter: World',
 'dragonsdogmadarkarisen': 'Dragons Dogma - Dark Arisen',
 'monacowhatsyoursismine': "Monaco: What's Yours Is Mine",
 'teamfortressii': 'Team Fortress 2',
 'dontstarve': "Don't Starve",
 'witness': 'The Witness',
 'darknessii': 'The Darkness II',
 'saintsrowiv': 'Saints Row IV',
 'bioshockiiremastered': 'BioShock 2 Remastered',
 'hitmanabsolution': 'Hitman Absolution',
 'falloutiiigameofyearedition': 'Fallout 3: Game of the Year Edition',
 'sanctumii': 'Sanctum 2',
 'southparkstickoftruth': 'South Park: The Stick of Truth',
 'bureauxcomdeclassified': 'The Bureau: XCOM Declassified',
 'segamegadriveandgenesisclassics': 'SEGA Mega Drive and Genesis Classics',
 'saintsrowii': 'Saints Row 2',
 'brothersataleoftwosons': 'Brothers - A Tale of Two Sons',
 'madmax': 'Mad Max',
 'defenceallianceii': 'Defence Alliance 2',
 'middleearthshadowofwar': 'Middle-earth™: Shadow of War™',
 'shadowrunreturns': 'Shadowrun Returns',
 'grimdawn': 'Grim Dawn',
 'bindingofisaac': 'The Binding of Isaac',
 'besiege': 'Besiege',
 'darksoulsiischolaroffirstsin': 'Dark Souls II: Scholar of the First Sin',
 'bioshock': 'BioShock™',
 'hyperlightdrifter': 'Hyper Light Drifter',
 'plagueincevolved': 'Plague Inc: Evolved',
 'hacknet': 'Hacknet',
 'starwarsknightsofoldrepublic': 'Star Wars: Knights of the Old Republic',
 'grandtheftautoiv': 'Grand Theft Auto IV',
 'batmanarkhamorigins': 'Batman™: Arkham Origins',
 'pillarsofeternityheroedition': 'Pillars of Eternity Hero Edition',
 'fez': 'FEZ',
 'halflife': 'Half-Life',
 'chivalrymedievalwarfare': 'Chivalry: Medieval Warfare',
 'doometernal': 'Doom Eternal',
 'gunsoficarusonline': 'Guns of Icarus Online',
 'planetcoaster': 'Planet Coaster',
 'alanwake': 'Alan Wake',
 'kingdomcomedeliverance': 'Kingdom Come: Deliverance',
 'tomoon': 'To The Moon',
 'deusexhumanrevolutiondirectorscut': "Deus Ex: Human Revolution - Director's Cut",
 'halflifeisource': 'Half-Life 1: Source',
 'markofninja': 'Mark of the Ninja',
 'starwarsjedifallenorder': 'STAR WARS Jedi: Fallen Order™',
 'shovelknighttreasuretrove': 'Shovel Knight: Treasure Trove',
 'bindingofisaacrebirth': 'The Binding of Isaac Rebirth',
 'counterstrikesource': 'Counter-Strike: Source',
 'sidmeierscivilizationiiicompleteedition': "Sid Meier's Civilization III Complete Edition",
 'farcryiii': 'Far Cry 3',
 'deadspace': 'Dead Space',
 'frostpunk': 'Frostpunk',
 'alienisolation': 'Alien: Isolation',
 'ageofwondersiii': 'Age of Wonders III',
 'halomasterchiefcollection': 'Halo: The Master Chief Collection',
 'elitedangerous': 'Elite: Dangerous',
 'pathofexile': 'Path of Exile',
 'banished': 'Banished',
 'dirtrally': 'DiRT Rally',
 'horizonzerodawncompleteedition': 'Horizon Zero Dawn™ Complete Edition',
 'oriandblindforest': 'Ori and the Blind Forest',
 'astoryaboutmyuncle': 'A Story About My Uncle',
 'soma': 'SOMA',
 'bioshockii': 'BioShock® 2',
 'endlessspacecollection': 'Endless Space Collection',
 'totalwarshogunii': 'Total War SHOGUN 2',
 'ahatintime': 'A Hat in Time',
 'dustanelysiantail': 'Dust: An Elysian Tail',
 'titanquestanniversaryedition': 'Titan Quest Anniversary Edition',
 'swapper': 'Swapper, The',
 'sniperelitevii': 'Sniper Elite V2',
 'castlecrashers': 'Castle Crashers',
 'layersoffear': 'Layers of Fear',
 'dirtiiicompleteedition': 'DiRT 3: Complete Edition',
 'flameinflood': 'The Flame in the Flood',
 'owlboy': 'Owlboy',
 'antichamber': 'Antichamber',
 'redorchestraiiheroesofstalingradwithrisingstorm': 'Red Orchestra 2: Heroes of Stalingrad with Rising Storm',
 'gridii': 'GRID 2',
 'braid': 'Braid',
 'jotunvalhallaedition': 'Jotun: Valhalla Edition',
 'dotaiitest': 'Dota 2 Test',
 'amnesiaamachineforpigs': 'Amnesia: A Machine For Pigs',
 'sinsofasolarempirerebellion': 'Sins of a Solar Empire: Rebellion',
 'arksurvivalevolved': 'ARK: Survival Evolved',
 'crysisiimaximumedition': 'Crysis® 2 Maximum Edition',
 'oddworldabesoddysee': "Oddworld: Abe's Oddysee",
 'northgard': 'Northgard',
 'satellitereign': 'Satellite Reign',
 'spaceengineers': 'Space Engineers',
 'invisibleinc': 'Invisible, Inc.',
 'lanoire': 'LA Noire',
 'orcsmustdieii': 'Orcs Must Die! 2',
 'wastelandiidirectorscut': "Wasteland 2: Director's Cut",
 'wolfensteiniinewcolossus': 'Wolfenstein II: The New Colossus',
 'visceracleanupdetailshadowwarrior': 'Viscera Cleanup Detail: Shadow Warrior',
 'slayspire': 'Slay the Spire',
 'farcryiv': 'Far Cry® 4',
 'warframe': 'Warframe',
 'bayonetta': 'Bayonetta',
 'burnoutparadiseultimatebox': 'Burnout Paradise: The Ultimate Box',
 'shadowtacticsbladesofshogun': 'Shadow Tactics: Blades of the Shogun',
 'deathstranding': 'Death Stranding',
 'finalfantasyxvwindowsedition': 'FINAL FANTASY XV WINDOWS EDITION',
 'playerunknownsbattlegrounds': "PLAYERUNKNOWN'S BATTLEGROUNDS ",
 'riskofrain': 'Risk of Rain',
 'returnofobradinn': 'Return of the Obra Dinn',
 'wolfamongus': 'The Wolf Among Us',
 'batmanarkhamknight': 'Batman: Arkham Knight',
 'eurotrucksimulatorii': 'Euro Truck Simulator 2',
 'gunpoint': 'Gunpoint',
 'shadowoftombraider': 'Shadow of the Tomb Raider',
 'theyarebillions': 'They Are Billions',
 'quantumbreak': 'Quantum Break',
 'entergungeon': 'Enter the Gungeon',
 'grimfandangoremastered': 'Grim Fandango Remastered',
 'kingdomclassic': 'Kingdom: Classic',
 'leftivdead': 'Left 4 Dead',
 'spelunky': 'Spelunky',
 'intobreach': 'Into the Breach',
 'broforce': 'BROFORCE',
 'middleearthshadowofmordor': 'Middle-earth™: Shadow of Mordor™',
 'dotaii': 'Dota 2',
 'crusaderkingsiisouthindianportraitsvyearanniversarygift': 'Crusader Kings II: South Indian Portraits 5 Year Anniversary Gift',
 'borderlands': 'Borderlands',
 'masseffectii': 'Mass Effect 2',
 'sunlesssea': 'Sunless Sea',
 'warhammeriv0000spacemarine': 'Warhammer 40,000: Space Marine',
 'deusexgameofyearedition': 'Deus Ex: Game of the Year Edition',
 'maxpayneiii': 'Max Payne 3',
 'psychonautsdemo': 'Psychonauts Demo',
 'metroexodus': 'Metro Exodus',
 'outerworlds': 'The Outer Worlds',
 'shadowrundragonfalldirectorscut': "Shadowrun: Dragonfall - Director's Cut",
 'scribblenautsunlimited': 'Scribblenauts Unlimited',
 'systemshockii': 'System Shock™ 2',
 'roguelegacy': 'Rogue Legacy',
 'worldofgoo': 'World of Goo',
 'okamihddashenjuejingban': 'ŌKAMI HD / 大神 絶景版',
 'keeptalkingandnobodyexplodes': 'Keep Talking and Nobody Explodes',
 'cavestoryplus': 'Cave Story+',
 'halflifeblueshift': 'Half-Life: Blue Shift',
 'totalwarwarhammer': 'Total War™: WARHAMMER®',
 'paydayheist': 'PAYDAY The Heist',
 'mafiaii': 'Mafia II',
 'endlesslegendclassicedition': 'Endless Legend - Classic Edition',
 'grid': 'GRID\x99',
 'valkyriachronicles': 'Valkyria Chronicles™',
 'hitmangameofyearedition': 'Hitman Game of the Year Edition',
 'elderscrollsvskyrimdawnguard': 'The Elder Scrolls V: Skyrim - Dawnguard',
 'metalgearsolidvgroundzeroes': 'Metal Gear Solid V: Ground Zeroes',
 'alanwakesamericannightmare': "Alan Wake's American Nightmare",
 'elderscrollsvskyrimdragonborn': 'The Elder Scrolls V: Skyrim - Dragonborn',
 'legolordofrings': 'LEGO Lord of the Rings',
 'halflifeopposingforce': 'Half-Life: Opposing Force',
 'viidaystodie': '7 Days to Die',
 'spacechem': 'Spacechem',
 'borderlandssecretarmoryofgeneralknoxx': 'Borderlands: The Secret Armory of General Knoxx',
 'vvvvvv': 'VVVVVV',
 'companyofheroesopposingfronts': 'Company of Heroes: Opposing Fronts',
 'metrolastlightredux': 'Metro: Last Light Redux',
 'walkingdeadseasontwo': 'The Walking Dead: Season Two',
 'warhammerendtimesvermintide': 'Warhammer: End Times - Vermintide',
 'grandtheftautosanandreas': 'Grand Theft Auto - San Andreas',
 'killingfloorii': 'Killing Floor 2',
 'galacticcivilizationsiiultimateedition': 'Galactic Civilizations II: Ultimate Edition',
 'control': 'Control',
 'pyre': 'Pyre',
 'awesomenautsiidmoba': 'Awesomenauts - the 2D moba',
 'dungeonsii': 'Dungeons 2',
 'feariii': 'F.E.A.R. 3',
 'finalfantasyxxiihdremaster': 'FINAL FANTASY X/X-2 HD Remaster',
 'wolfensteinoldblood': 'Wolfenstein: The Old Blood',
 'borderlandsclaptrapsrobotrevolution': "Borderlands: Claptrap's Robot Revolution",
 'shadowwarriorii': 'Shadow Warrior 2',
 'redfactionarmageddon': 'Red Faction®: Armageddon\x99',
 'bannersaga': 'The Banner Saga',
 'whatremainsofedithfinch': 'What Remains of Edith Finch',
 'torchlight': 'Torchlight',
 'homefront': 'Homefront',
 'elderscrollsvskyrimhearthfire': 'The Elder Scrolls V: Skyrim - Hearthfire',
 'stalkershadowofchernobyl': 'S.T.A.L.K.E.R. Shadow of Chernobyl',
 'farcryv': 'Far Cry® 5',
 'nuclearthrone': 'Nuclear Throne',
 'tropicoiii': 'Tropico 3',
 'elderscrollsivobliviongameofyearedition': 'The Elder Scrolls IV: Oblivion® Game of the Year Edition',
 'littlenightmares': 'Little Nightmares',
 'sidmeierscivilizationvbravenewworld': "Sid Meier's Civilization V: Brave New World",
 'sleepingdogsdefinitiveedition': 'Sleeping Dogs: Definitive Edition',
 'jetsetradio': 'Jet Set Radio',
 'kentuckyroutezero': 'Kentucky Route Zero',
 'teamfortressclassic': 'Team Fortress Classic',
 'thief': 'THIEF',
 'feariiprojectorigin': 'F.E.A.R. 2: Project Origin',
 'oxenfree': 'Oxenfree',
 'dungeondefenders': 'Dungeon Defenders',
 'killerisdeadnightmareedition': 'Killer is Dead - Nightmare Edition',
 'valvecompletepack': 'Valve Complete Pack',
 'slimerancher': 'Slime Rancher',
 'paydayii': 'PAYDAY 2',
 'injusticegodsamongusultimateedition': 'Injustice: Gods Among Us - Ultimate Edition',
 'aplaguetaleinnocence': 'A Plague Tale: Innocence',
 'cryptofnecrodancer': 'Crypt of the Necrodancer',
 'serioussamiiibfe': 'Serious Sam 3: BFE',
 'mountandbladewarband': 'Mount & Blade: Warband',
 'companyofheroestalesofvalor': 'Company of Heroes: Tales of Valor',
 'talesfromborderlands': 'Tales from the Borderlands',
 'masseffect': 'Mass Effect',
 'metroii0iiiiiiredux': 'Metro 2033 Redux',
 'mountandbladeiibannerlord': 'Mount & Blade II: Bannerlord',
 'hotlinemiamiiiwrongnumber': 'Hotline Miami 2: Wrong Number',
 'abzu': 'ABZU',
 'dmcdevilmaycry': 'DMC - Devil May Cry',
 'deadislandgameofyearedition': 'Dead Island - Game of the Year Edition',
 'crosscode': 'CrossCode',
 'guacameleegoldedition': 'Guacamelee! Gold Edition',
 'legendofgrimrock': 'Legend of Grimrock',
 'goatsimulator': 'Goat Simulator',
 'thomaswasalone': 'Thomas Was Alone',
 'vanishingofethancarter': 'The Vanishing of Ethan Carter',
 'ninokuniiirevenantkingdom': 'Ni no Kuni™ II: Revenant Kingdom',
 'warhammeriv0000dawnofwargameofyearedition': 'Warhammer® 40,000: Dawn of War® - Game of the Year Edition',
 'stalkercallofpripyat': 'S.T.A.L.K.E.R. Call of Pripyat',
 'dirtshowdown': 'DiRT Showdown',
 'outerwilds': 'Outer Wilds',
 'crusaderkingsiiafricanportraits': 'Crusader Kings II: African Portraits',
 'rememberme': 'Remember Me',
 'guacameleesuperturbochampionshipedition': 'Guacamelee! Super Turbo Championship Edition',
 'totalwarwarhammerii': 'Total War: WARHAMMER II',
 'handoffate': 'Hand of Fate',
 'saltandsanctuary': 'Salt and Sanctuary',
 'serioussamhd': 'Serious Sam HD',
 'riskofrainii': 'Risk of Rain 2',
 'minimetro': 'Mini Metro',
 'machinarium': 'Machinarium',
 'callofjuarezgunslinger': 'Call of Juarez: Gunslinger',
 'falloutapostnuclearroleplayinggame': 'Fallout: A Post Nuclear Role Playing Game',
 'companyofheroeslegacyedition': 'Company of Heroes - Legacy Edition',
 'brokenage': 'Broken Age',
 'xcomufodefense': 'X-COM: UFO Defense',
 'shadowrunhongkongextendededition': 'Shadowrun Hong Kong - Extended Edition',
 'grandtheftautovicecity': 'Grand Theft Auto - Vice City',
 'overlord': 'Overlord\x99',
 'mafiaiii': 'MAFIA III',
 'hellyeahwrathofdeadrabbit': 'Hell Yeah! Wrath of the Dead Rabbit',
 'deadlight': 'DEADLIGHT',
 'finalfantasyvii': 'FINAL FANTASY VII',
 'binarydomain': 'Binary Domain',
 'orcsmustdie': 'Orcs Must Die!',
 'counterstrikeconditionzero': 'Counter-Strike: Condition Zero',
 'armello': 'Armello',
 'orwell': 'Orwell',
 'greedfall': 'GreedFall',
 'deeprockgalactic': 'Deep Rock Galactic',
 'humanfallflat': 'Human: Fall Flat',
 'falloutnewvegasdeadmoney': 'Fallout New Vegas: Dead Money',
 'falloutnewvegashonesthearts': 'Fallout New Vegas: Honest Hearts',
 'assassinscreedodyssey': "Assassin's Creed Odyssey",
 'elderscrollsiiimorrowindgameofyearedition': 'The Elder Scrolls III: Morrowind® Game of the Year Edition',
 'paydayiiultimateedition': 'PAYDAY 2: Ultimate Edition',
 'nightinwoods': 'Night In The Woods',
 'lordofringswarinnorth': 'Lord of the Rings: War in the North',
 'deadspaceii': 'Dead Space 2',
 'outland': 'Outland',
 'alphaprotocol': 'Alpha Protocol',
 'legohobbit': 'LEGO® The Hobbit™',
 'armaiii': 'Arma 3',
 'watchdogsii': 'Watch_Dogs® 2',
 'assassinscreedorigins': "Assassin's Creed® Origins",
 'furi': 'Furi',
 'superbrothersswordandsworceryep': 'Superbrothers: Sword & Sworcery EP',
 'borderlandsmadmoxxisunderdomeriot': "Borderlands: Mad Moxxi's Underdome Riot",
 'sidmeierscivilizationiv': "Sid Meier's Civilization® IV",
 'styxmasterofshadows': 'Styx: Master of Shadows',
 'darksiders': 'Darksiders',
 'speedrunners': 'SpeedRunners',
 'titanquest': 'Titan Quest',
 'gonehome': 'Gone Home',
 'pokernightatinventory': 'Poker Night at the Inventory',
 'twopointhospital': 'Two Point Hospital',
 'snipereliteiii': 'Sniper Elite 3',
 'teleglitchdiemoreedition': 'Teleglitch: Die More Edition',
 'gangbeasts': 'Gang Beasts',
 'snipereliteiv': 'Sniper Elite 4',
 'deusexhumanrevolution': 'Deus Ex Human Revolution',
 'hitmanbloodmoney': 'Hitman Blood Money',
 'borderlandsgameofyearenhanced': 'Borderlands: Game of the Year Enhanced',
 'ashesofsingularityescalation': 'Ashes of the Singularity: Escalation',
 'murderedsoulsuspect': 'Murdered: Soul Suspect',
 'fearextractionpoint': 'F.E.A.R.: Extraction Point',
 'fearperseusmandate': 'F.E.A.R.: Perseus Mandate',
 'renegadeops': 'Renegade Ops',
 'metalgearrisingrevengeance': 'METAL GEAR RISING: REVENGEANCE',
 'vampyr': 'Vampyr',
 'gris': 'GRIS',
 'darksidersiideathinitiveedition': 'Darksiders II Deathinitive Edition',
 'companyofheroes': 'Company of Heroes',
 'finalfantasyix': 'FINAL FANTASY IX',
 'talesofberseria': 'Tales of Berseria',
 'falloutnewvegascouriersstash': "Fallout New Vegas - Courier's Stash",
 'steamworldheist': 'SteamWorld Heist',
 'trineenchantededition': 'Trine Enchanted Edition',
 'anomalywarzoneearth': 'Anomaly Warzone Earth',
 'naturalselectionii': 'Natural Selection 2',
 'skullgirls': 'Skullgirls',
 'laracroftandguardianoflight': 'Lara Croft and the Guardian of Light',
 'vampiremasqueradebloodlines': 'Vampire: The Masquerade - Bloodlines',
 'crawl': 'Crawl',
 'planetaryannihilation': 'Planetary Annihilation',
 'homeworldremasteredcollection': 'Homeworld Remastered Collection',
 'redsolstice': 'The Red Solstice',
 'grandtheftautoiii': 'Grand Theft Auto 3',
 'celeste': 'Celeste',
 'neveralonekisimaingitchuna': 'Never Alone (Kisima Ingitchuna)',
 'dungeonofendless': 'Dungeon of the Endless',
 'ageofempiresiiicompletecollection': 'Age of Empires® III: Complete Collection',
 'medalofhonor': 'Medal of Honor',
 'vikingbattleforasgard': 'Viking Battle for Asgard',
 'ruiner': 'RUINER',
 'lethalleague': 'Lethal League',
 'reus': 'Reus',
 'starwarsknightsofoldrepubliciisithlords': 'STAR WARS®: Knights of the Old Republic™ II - The Sith Lords™',
 'rysesonofrome': 'Ryse: Son of Rome',
 'childoflight': 'Child of Light',
 'hades': 'Hades',
 'sanctum': 'Sanctum',
 'littleinferno': 'Little Inferno',
 'residenteviliibiohazardreiistandardedition': 'RESIDENT EVIL 2 / BIOHAZARD RE:2 Standard Edition',
 'doorkickers': 'Door Kickers',
 'polybridge': 'Poly Bridge',
 'rage': 'RAGE',
 'turingtest': 'The Turing Test',
 'sidmeierscivilizationbeyondearth': "Sid Meier's Civilization: Beyond Earth",
 'armaii': 'ArmA 2',
 'minionmasters': 'Minion Masters',
 'legendofheroestrailsinsky': 'The Legend of Heroes: Trails in the Sky',
 'xcomenemywithin': 'XCOM: Enemy Within',
 'lastremnant': 'The Last Remnant',
 'borderlandsgameofyeareditionenhanced': 'Borderlands Game of the Year Edition Enhanced',
 'overcooked': 'Overcooked',
 'assassinscreedivblackflag': 'Assassin’s Creed® IV Black Flag™',
 'baldursgateenhancededition': "Baldur's Gate: Enhanced Edition",
 'dayoftentacleremastered': 'Day of the Tentacle Remastered',
 'snakepass': 'Snake Pass',
 'starwarsjediknightjediacademy': 'Star Wars®: Jedi Knight®: Jedi Academy\x99',
 'gianasisterstwisteddreams': 'Giana Sisters: Twisted Dreams',
 'elex': 'ELEX',
 'notimetoexplainremastered': 'No Time To Explain Remastered',
 'riseniidarkwaters': 'Risen 2 Dark Waters',
 'kenshi': 'Kenshi',
 'enslavedodysseytowestpremiumedition': 'Enslaved: Odyssey to the West Premium Edition',
 'frozensynapse': 'Frozen Synapse',
 'niohcompleteedition': 'Nioh: Complete Edition',
 'residenteviliv': 'Resident Evil 4',
 'laracroftandtempleofosiris': 'Lara Croft and the Temple of Osiris',
 'baldursgateiienhancededition': "Baldur's Gate II: Enhanced Edition",
 'farcryiiiblooddragon': 'Far Cry 3: Blood Dragon',
 'hammerwatch': 'Hammerwatch',
 'octopathtraveler': 'OCTOPATH TRAVELER',
 'risen': 'Risen',
 'wehappyfew': 'We Happy Few',
 'starwarsbattlefrontiiclassicii00v': 'Star Wars: Battlefront 2 (Classic, 2005)',
 'superhexagon': 'Super Hexagon',
 'gamedevtycoon': 'Game Dev Tycoon',
 'momodorareverieundermoonlight': 'Momodora: Reverie Under the Moonlight',
 'overlordii': 'Overlord II',
 'warhammervermintideii': 'Warhammer: Vermintide 2',
 'kingdomnewlands': 'Kingdom: New Lands',
 'kholat': 'Kholat',
 'legendofgrimrockii': 'Legend of Grimrock II',
 'stalkerclearsky': 'S.T.A.L.K.E.R. Clear Sky',
 'thiefgold': 'Thief Gold',
 'onefingerdeathpunch': 'One Finger Death Punch',
 'hitmaniisilentassassin': 'Hitman 2 - Silent Assassin',
 'rebelgalaxy': 'Rebel Galaxy',
 'racesun': 'Race the Sun',
 'fear': 'F.E.A.R',
 'escapists': 'The Escapists',
 'strider': 'Strider',
 'audiosurf': 'AudioSurf',
 'southparkfracturedbutwhole': 'South Park The Fractured But Whole',
 'incredibleadventuresofvanhelsing': 'The Incredible Adventures of Van Helsing',
 'sidmeierscivilizationivcolonization': "Sid Meier's Civilization IV: Colonization",
 'hardresetextendededition': 'Hard Reset Extended Edition',
 'thesurge': 'The Surge',
 'survivingmars': 'Surviving Mars',
 'everspace': 'EVERSPACE™',
 'deponia': 'Deponia',
 'residentevilbiohazardhdremaster': 'Resident Evil / biohazard HD REMASTER',
 'yakuza0': 'Yakuza 0',
 'thisispolice': 'This Is the Police'}